export const HeaderMenuAction = {
  LOGOUT: 'logout'
}

export const HeaderMenuLabel = {
  AGENTS: 'Agents',
  SHOW_AGENTS: 'Show Agents',
  AGENT_STATUS: 'Agent Status',
  TASKS: 'Tasks',
  SHOW_TASKS: 'Show Tasks',
  PRECONFIGURED_TASKS: 'Preconfigured Tasks',
  SUPERTASKS: 'Supertasks',
  IMPORT_SUPERTASK: 'Import Supertask',
  CHUNK_ACTIVITY: 'Chunk activity',
  HASHLISTS: 'Hashlists',
  SHOW_HASHLISTS: 'Hashlists',
  SUPERHASHLISTS: 'Superhashlists',
  SEARCH_HASH: 'Search Hash',
  SHOW_CRACKS: 'Show cracks',
  FILES: 'Files',
  WORDLISTS: 'Wordlists',
  RULES: 'Rules',
  OTHER: 'Other',
  USERS: 'Users',
  ALL_USERS: 'All users',
  GLOBAL_PERMISSIONS: 'Global Permissions',
  ACCESS_GROUPS: 'Access Groups',
  CONFIG: 'Config',
  SETTINGS: 'Settings',
  HASHTYPES: 'Hashtypes',
  HEALTH_CHECKS: 'Health Checks',
  LOG: 'Log',
  BINARIES: 'Binaries',
  CRACKERS: 'Crackers',
  PREPROCESSORS: 'Preprocessors',
  AGENT_BINARIES: 'Agent Binaries',
}