export const RowActionMenuLabel = {
  ACTIVATE_USER: 'Activate User',
  ACTIVATE_AGENT: 'Activate Agent',
  ACTIVATE_NOTIFICATION: 'Activate Notification',
  DEACTIVATE_USER: 'Deactivate User',
  DEACTIVATE_AGENT: 'Deactivate Agent',
  DEACTIVATE_NOTIFICATION: 'Deactivate Notification',
  EDIT_AGENT: 'Edit Agent',
  EDIT_NOTIFICATION: 'Edit Notification',
  EDIT_TASK: 'Edit Task',
  EDIT_SUBTASKS: 'Edit Subtasks',
  EDIT_HASHLIST: 'Edit Hashlist',
  EDIT_SUPERHASHLIST: 'Edit Superhashlist',
  EDIT_FILE: 'Edit File',
  EDIT_PREPROCESSOR: 'Edit Preprocessor',
  EDIT_AGENTBINARY: 'Edit Agent Binary',
  EDIT_HEALTHCHECK: 'Edit Health Check',
  EDIT_USER: 'Edit User',
  EDIT_ACCESSGROUP: 'Edit Access Group',
  DELETE_AGENT: 'Delete Agent',
  DELETE_NOTIFICATION: 'Delete Notification',
  DELETE_CRACKER: 'Delete Cracker',
  DELETE_TASK: 'Delete Task',
  DELETE_HASHLIST: 'Delete Hashlist',
  DELETE_HASHTYPE: 'Delete Hashtype',
  DELETE_SUPERHASHLIST: 'Delete Superhashlist',
  DELETE_FILE: 'Delete File',
  DELETE_PREPROCESSOR: 'Delete Preprocessor',
  DELETE_AGENTBINARY: 'Delete Agent Binary',
  DELETE_HEALTHCHECK: 'Delete Health Check',
  DELETE_USER: 'Delete User',
  DELETE_ACCESSGROUP: 'Delete Access Group',
  COPY_TO_TASK: 'Copy to Task',
  COPY_TO_PRETASK: 'Copy to Pretask',
  ARCHIVE_TASK: 'Archive Task',
  IMPORT_HASHLIST: 'Import Hashlist',
  EXPORT_HASHLIST: 'Export Hashlist',
  NEW_VERSION: 'Add Version'
};

export const RowActionMenuAction = {
  EDIT: 'edit',
  DELETE: 'delete',
  ARCHIVE: 'archive',
  COPY_TO_TASK: 'copy-to-task',
  COPY_TO_PRETASK: 'copy-to-pretask',
  EDIT_SUBTASKS: 'edit-subtasks',
  NEW: 'new',
  IMPORT: 'import',
  EXPORT: 'export',
  ACTIVATE: 'activate',
  DEACTIVATE: 'deactivate'
};

export const RowActionMenuIcon = {
  EDIT: 'edit',
  DELETE: 'delete',
  NEW: 'add',
  IMPORT: 'arrow_upwards',
  EXPORT: 'arrow_downward',
  COPY: 'content_copy',
  ARCHIVE: 'archive',
  ACTIVATE: 'check_circle',
  DEACTIVATE: 'remove_circle'
};
