export const RowActionMenuLabel = {
  ACTIVATE_USER: 'Activate User',
  ACTIVATE_AGENT: 'Activate Agent',
  ACTIVATE_NOTIFICATION: 'Activate Notification',
  APPLY_HASHLIST: 'Apply Hashlist',
  DEACTIVATE_USER: 'Deactivate User',
  DEACTIVATE_AGENT: 'Deactivate Agent',
  DEACTIVATE_NOTIFICATION: 'Deactivate Notification',
  EDIT_AGENT: 'Edit Agent',
  EDIT_NOTIFICATION: 'Edit Notification',
  EDIT_PRETASK: 'Edit Pretask',
  EDIT_TASK: 'Edit Task',
  EDIT_SUPERTASK: 'Edit Supertask',
  EDIT_SUBTASKS: 'Edit Subtasks',
  EDIT_HASHLIST: 'Edit Hashlist',
  EDIT_HASHTYPE: 'Edit Hashtype',
  EDIT_SUPERHASHLIST: 'Edit Superhashlist',
  EDIT_FILE: 'Edit File',
  DOWNLOAD_FILE: 'Download File',
  EDIT_PREPROCESSOR: 'Edit Preprocessor',
  EDIT_AGENTBINARY: 'Edit Agent Binary',
  VIEW_HEALTHCHECK: 'View Health Check',
  EDIT_USER: 'Edit User',
  EDIT_ACCESSGROUP: 'Edit Access Group',
  EDIT_PERMISSION: 'Edit Permission Group',
  DELETE_AGENT: 'Delete Agent',
  DELETE_NOTIFICATION: 'Delete Notification',
  DELETE_CRACKER: 'Delete Cracker',
  DELETE_PRETASK: 'Delete Pretask',
  DELETE_TASK: 'Delete Task',
  DELETE_SUPERTASK: 'Delete Supertask',
  DELETE_HASHLIST: 'Delete Hashlist',
  DELETE_HASHTYPE: 'Delete Hashtype',
  DELETE_SUPERHASHLIST: 'Delete Superhashlist',
  DELETE_FILE: 'Delete File',
  DELETE_PREPROCESSOR: 'Delete Preprocessor',
  DELETE_AGENTBINARY: 'Delete Agent Binary',
  DELETE_HEALTHCHECK: 'Delete Health Check',
  DELETE_USER: 'Delete User',
  DELETE_ACCESSGROUP: 'Delete Access Group',
  DELETE_PERMISSION: 'Delete Permission Group',
  DELETE_VOUCHER: 'Delete Voucher',
  DELETE_ERROR: 'Delete Error',
  COPY_TO_TASK: 'Copy to Task',
  COPY_TO_PRETASK: 'Copy to Pretask',
  ARCHIVE_TASK: 'Archive Task',
  IMPORT_HASHLIST: 'Import Hashlist',
  IMPORT_HASHLISTS: 'Import Hashlists',
  EXPORT_HASHLIST: 'Export Hashlist',
  EXPORT_HASHLISTS: 'Export Hashlists',
  NEW_VERSION: 'Add Version',
  DOWNLOAD_AGENT: 'Download Agent Binary',
  COPY_LINK_BINARY: 'Copy link Agent Binary',
  UNARCHIVE_TASK: 'Unarchive Task',
  UNASSIGN_AGENT: 'Unassign Agent',
  UNASSIGN_USER: 'Unassign User',
  UNASSIGN_PRETASK: 'Unassign Pretask',
  RESET_CHUNK: 'Reset Task Chunk',
  REMOVE_ACCESSGROUP_AGENT: 'Remove Agent',
  REMOVE_ACCESSGROUP_USER: 'Remove User',
  ARCHIVE_PRETASK: 'Archive PreTask',
  UNARCHIVE_PRETASK: 'Unarchive PreTask'
};

export const RowActionMenuAction = {
  EDIT: 'edit',
  DELETE: 'delete',
  COPY_LINK: 'copy-link',
  ARCHIVE: 'archive',
  APPLY_TO_HASHLIST: 'apply-to-hashlist',
  COPY_TO_TASK: 'copy-to-task',
  COPY_TO_PRETASK: 'copy-to-pretask',
  EDIT_TASKS: 'edit-tasks',
  EDIT_SUBTASKS: 'edit-subtasks',
  NEW: 'new',
  IMPORT: 'import',
  EXPORT: 'export',
  ACTIVATE: 'activate',
  DEACTIVATE: 'deactivate',
  DOWNLOAD: 'download',
  UNARCHIVE: 'unrachive',
  RESET: 'reset',
  VIEW: 'view'
};

export const RowActionMenuIcon = {
  EDIT: 'edit',
  DELETE: 'delete',
  NEW: 'add',
  IMPORT: 'arrow_upwards',
  EXPORT: 'arrow_downward',
  COPY: 'content_copy',
  ARCHIVE: 'archive',
  UNARCHIVE: 'unarchive',
  ACTIVATE: 'check_circle',
  DEACTIVATE: 'remove_circle',
  DOWNLOAD: 'file_download',
  RESET: 'restore',
  VIEW: 'preview'
};
